### ISSUE TITLE
provide a compiled js file

### ISSUE THREAD

**Issue by danielortiz** [nathanstitt/object-factory-bot#1]
Hi,
I'm using it along with create-react-app and I'm having a problem that when I try to build the project I get an error because create-react-app doesn't compile libraries and apparently there's no way around it besides compiling it myself and having it in my codebase (urgh) AND the library providing a compiled version 

Can it be done?

**Comment by nathanstitt** [comment]
Hey @danielortiz thanks for the suggestion. I've just converted the lib to typescript which as a side-effect provides pre-compiled JS files as well.

version `0.7.4`  should have it included
